// Mocks generated by Mockito 5.4.6 from annotations
// in d3_wallet/test/data/remote/interceptors/auth_interceptor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:d3_wallet/data/bean/app_configurations/app_configurations.dart' as _i4;
import 'package:d3_wallet/data/repositories/app_configs_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AppConfigsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppConfigsRepository extends _i1.Mock implements _i2.AppConfigsRepository {
  MockAppConfigsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> saveLocalPassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocalPassword, [password]),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> saveAppConfigurations(_i4.AppConfigurations? appConfigurations) =>
      (super.noSuchMethod(
            Invocation.method(#saveAppConfigurations, [appConfigurations]),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<_i4.AppConfigurations?> retrieveAppConfigurations() =>
      (super.noSuchMethod(
            Invocation.method(#retrieveAppConfigurations, []),
            returnValue: _i3.Future<_i4.AppConfigurations?>.value(),
          )
          as _i3.Future<_i4.AppConfigurations?>);

  @override
  _i3.Future<dynamic> clearAppData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAppData, []),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);
}
